services:
  66bit.frontend:
    image: 66bit.frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - 66bit.backend

  66bit.backend:
    image: backend:latest
    container_name: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=flywotbl@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=Wertyqin923134
    ports:
      - "8082:80"
    depends_on:
      - "postgres"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pg-data: 
  pgadmin: 

